name: Refresh drives

on:
#  schedule:
#    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      expiry:
        description: "Active time before ghosting content"
        required: false
        default: "1h"
      refresh_interval:
        description: "Time before refreshing ghosted content"
        required: false
        default: "3d"
      args:
        description: "Arguments to pass to nexutils.exe"
        required: false
        default: ""
jobs:
  run-nexutils:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: media_wus2
            sas_key: MEDIA_WUS2_SAS_URL

    steps:
      - name: Download nexutils.exe
        run: Invoke-WebRequest -Uri "https://github.com/Xollective/PublicToolsRelease/releases/download/latest/nexutils.exe" -OutFile nexutils.exe

      - name: Run nexutils.exe with secret
        run: .\nexutils.exe dehydrate --uri "$env:SAS_URL" --refresh-interval ${{ inputs.refresh_interval || '5d' }} --expiry ${{ inputs.expiry || '1h' }} ${{ inputs.args }}
        env:
          SAS_URL: ${{ secrets[matrix.sas_key] }}
