name: Run nexutils with multiple secrets

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-nexutils:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: media_wus2
            sas_key: MEDIA_WUS2_SAS_URL

    steps:
      - name: Download nexutils.exe
        run: Invoke-WebRequest -Uri "https://github.com/Xollective/PublicToolsRelease/releases/download/latest/nexutils.exe" -OutFile nexutils.exe

      - name: Run nexutils.exe with secret
        run: .\nexutils.exe dehydrate --uri "$env:SAS_URL"
        env:
          SAS_URL: ${{ secrets[matrix.sas_key] }}